version: 0.0

os: linux
files:
  - source: ./
    destination: ./myFolderHereItIs
hooks:
   BeforeInstall:
      - location: prepare_dir.sh
        runas: root
   ApplicationStart:
     - location: run_app.sh       
       runas: root 
