version: 0.0
os: linux
files:
  - source: ./
    destination: /tmp/social-credit-system/
hooks:
   BeforeInstall:
      - location: ./prepare_dir.sh
        runas: root
   ApplicationStart:
     - location: ./run_app.sh       
       runas: root 
